name: Onboarding Pipeline Test Workflow

on:
    workflow_dispatch:


jobs:
    OnboardingPipelineTest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Load values
              run: echo "Loading customer values from .github/workflows/values.json"

            - name: Run onboarding pipeline test
              run: echo "Running onboarding pipeline test with customer values"
